x-env-file: &env-file
  env_file: .env.dev

services:
  ic_frontend:
    build:
      context: ./ic_frontend
      dockerfile: dockerfile
    image: kalebrs/ic-frontend:latest
    <<: *env-file
    environment:
      - ENV=dev
      - BACKEND_URL=http://ic_backend:8051
    depends_on:
      ic_backend:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -v http://localhost:8501/_stcore/health || echo 'Health check failed' >&2"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "8501:8501"

  ic_backend:
    build:
      context: ./ic_backend
      dockerfile: dockerfile
    image: kalebrs/ic-backend:latest
    <<: *env-file
    environment:
      - ENV=dev
      - MINIO_URL=ic_minio:9000
      - MINIO_SECURE=false
    depends_on:
      ic_minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8051/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s
    networks:
      - app-network
    ports:
      - "8051:8051"

  ic_minio:
    build:
      context: ./ic_minio
      dockerfile: dockerfile
    image: kalebrs/ic-minio:latest
    <<: *env-file
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./ic_nginx/data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes: {}
